### ISSUE TITLE
Experience data: make titel optional

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/experiencelogger#10]
Ich hätte standardmäßig pro Typ einen Titel gesetzt und das aktuelle Titel-Feld ggf. als optionalen Titel genutzt.
Heißt: die Titel der Typen (Opening Day, Model, etc.) werden hard gecoded oder unter Settings einmalig einstellt. Sie werden dann somit immer gleich angezeigt und es kann nicht passieren, dass mal Eröffnungstag und mal Eröffnungsdatum o.ä. eingetragen wird. Der Standard-Titel wird solange angezeigt, bis in dem optionalen Titel-Feld etwas eingetragen wird, was dann den Titel des Types bei dieser Attraktion einmalig & individuell überschreibt

**Comment by StevenPaw** [comment]
Made optional with 8378b5cda4fa4edbbb5ce269da21fdd93f126ae3
