### ISSUE TITLE
experience_markers add darker background

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/experiencelogger#115]
Some experience_markers are not clearly visible on bright images. Please add a shadow or semi-transparent background to the circle for better visibility
Example: 
![image](https://github.com/SP-Universe/experiencelogger/assets/29929054/8da52c78-b053-4532-b3af-153c44bd9dae)

**Comment by StevenPaw** [comment]
Fixed with aadf5760ee359e52bce9b77f9a2fa232c294e88f
