### ISSUE TITLE
Link to Experince

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/experiencelogger#15]
Auf der Experince Seite sollte man einen Link zur Experince einfügen können. Dann kann man von dem aus auf die offizielle Park-Seite mit der Attraktion kommen

**Comment by StevenPaw** [comment]
Partially added with 1cce0d4f19afe1975791939536a2e1bb709c64b5

**Comment by StevenPaw** [comment]
Added with 9e730e249c32057f049f32d5bbd226cc19e08483
