### ISSUE TITLE
Title doesn't support – and Umlaute

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/experiencelogger#21]
Das Minus oder Umlaute im Titel (bspw. bei _Colossos – Kampf der Giganten_) wird nicht unterstützt. Wenn man die Attraktion im Frontend öffnet, dann werden die Daten nicht geladen/ angezeigt

**Comment by StevenPaw** [comment]
Fixed with 3ec026bdbd9e51d7a5d5c9118b21b9dcd2243aa1
