### ISSUE TITLE
Override problem with two attractions with the same name

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/experiencelogger#24]
If several attractions have the same name, they are loaded incorrectly. E.g. the monorail of Europa-Park is also loaded if you want to open the monorail of Heide-Park. Maybe combine attractions and parks in web links?

**Comment by zwibblTV** [comment]
Second example: Koggenfahrt (Heide-Park & Hansa-Park)

**Comment by StevenPaw** [comment]
Fixed with 3ec026bdbd9e51d7a5d5c9118b21b9dcd2243aa1
