### ISSUE TITLE
Design: Hide wagon when only one is available or when "use wagons" is not selected

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/experiencelogger#45]
Style a Train without multiple wagons like this:
![image](https://user-images.githubusercontent.com/29929054/195985633-1c5b59ee-7025-496e-984f-ed69d9ffd0d9.png)

**Comment by StevenPaw** [comment]
Partially added with 9e730e249c32057f049f32d5bbd226cc19e08483
Wont fix further
