### ISSUE TITLE
Score: allow : and maybe add unit

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/experiencelogger#54]
For Space Scooter (Hansa-Park) as an example, the score is like 2:17 min. But you only may enter numbers. Thats why : should be allowed. Maybe add units for the backend too. For Space Scooter min, for Barracuda Slide m, ...

**Comment by StevenPaw** [comment]
Fixed with dde487d5a52cce1311b2e215df25256c4edf90ba
