### ISSUE TITLE
Links not working for two same named experiences

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/experiencelogger#79]
Ich wäre dafür, den Park in der URL aufzunehmen. Vielleicht gekürzt, dass man bei den Einstellungen zum Park eine Abkürzung eintragen kann.
"STE" statt "Stage Theater an der Elbe" und dass der Link dann auch so aufgebaut wird: places/experience/STE/die-eiskoenigin
Weil Monorail1, Monorail2 usw finde ich nicht schön und mit meiner Idee könnte man anhand des Links zumindest grob erahnen, in welchem Park man ist
Das soll verhindern, dass sich Attraktionen mit dem selben Namen beim aufrufen des Links überschreiben

**Comment by StevenPaw** [comment]
For now fixed with $filteredTitle . "-" . $this->ID;
Locationshortcuts are not possible if too many parks will be added. but will look further into it in the future

**Comment by StevenPaw** [comment]
Fixed with 6a5c018202b293a258b5b430140358cb5ba3ef4a
