### ISSUE TITLE
Break lines for long titles

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/experiencelogger#80]
Please add a line break, when a title is to long:
![Screenshot_20230406_132926_Chrome](https://user-images.githubusercontent.com/29929054/230364564-1bc55123-a23b-4aed-a00c-ea1c8acf7dc6.jpg)

**Comment by StevenPaw** [comment]
Added with 40f39161f6e9bfec5afa603c279c419b96f77ec5
