### ISSUE TITLE
link-log only newly entered areas / shows

### ISSUE THREAD

**Issue by zwibblTV** [SP-Universe/experiencelogger#89]
Please link log only one newly entered area or show. If you ride two or more attractions in the same ares / show, the area / show should only be logged once

**Comment by StevenPaw** [comment]
Fixed with 40f39161f6e9bfec5afa603c279c419b96f77ec5
Will not change the behaviour for stages for now. Only for areas

**Comment by zwibblTV** [comment]
Works fine, but also for several days...
Please check if the last linked lock was before the current day and if so, please add the linked log again

**Comment by StevenPaw** [comment]
Hopefully Fixed with 598acf4dea7ece5cc6b5886227a40992e99ed870

**Comment by zwibblTV** [comment]
Not yet working perfectly. If the linked log from the previous time (e.g. the day before) is identical to the new one, then the linked log is not logged on the new day

**Comment by StevenPaw** [comment]
Should be fixed with b4d7b151104503eedc71711399dc51aaeb016685
